version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: challenge_delivery
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    env_file:
      - .env
    links:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - challenge_delivery_data:/var/lib/postgresql/data
volumes:
  challenge_delivery_data: